#!/bin/bash
rm build/libs/*
rm latestbuild/*
echo "Building JMOD";
./gradlew build $* > /dev/null
rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi
cp build/libs/jmod*.jar libs
cd plugins

subs=($(ls . | grep JMOD-))
length=${#subs[@]}
for ((i = 0; i != length; i++)); do
	echo "Building Modules $((i + 1))/$length: ${subs[i]}";
	cd ${subs[i]}
	if [ "$(ls -A build/libs)" ]; then
		 rm build/libs/*
	fi
	./gradlew buildPlugin $* > /dev/null
	rc=$?; if [[ $rc != 0 ]]; then exit $rc; fi
	cd ..
done
cd ..

cp build/libs/jmod*.jar latestbuild/
cp plugins/JMOD-*/build/libs/*.jmodplugin latestbuild/
zip latestbuild/plugins.zip latestbuild/*.jmodplugin
