#!/bin/bash
nano -w /tmp/commitmsg

subs=($(ls . | grep JMOD-))
length=${#subs[@]}
for ((i = 0; i != length; i++)); do
	echo "Committing Modules $((i + 1))/$length: ${subs[i]}";
	cd ${subs[i]}
	git add .
	git commit -F /tmp/commitmsg
	git push origin
	cd ..
done

echo "Committing JMOD";
git add .
git commit -F /tmp/commitmsg
git push origin
